name: Lint And Doc check

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request_target:
    branches:
      - main
    paths:
      - '**/*.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch main
        run: |
          git fetch origin main

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            python:
              - ./**.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: |
          pip install flake8
          pip install flake8-bugbear
          pip install flake8-quotes

      - name: Run flake8
        run: |
          CHANGED_FILES="${{ steps.changed_files.outputs.python_all_changed_files }}"
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changed Python files: $CHANGED_FILES"
            make lint-only-diff CHANGED_FILES="$CHANGED_FILES"
          else
            echo "No Python files changed, skipping lint"
          fi

  DocCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install LazyLLM
        uses: ./.github/actions/setup

      - name: Run DocCheck
        run: |
          pip install -r tests/requirements.txt
          pytest --lf --last-failed-no-failures=all --durations=0 --reruns=2 -v tests/doc_check
